name: awesome_flutter_shaders
description: awesome flutter shaders, manual migration from https://www.shadertoy.com shaders one by one
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.10.0 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  shader_buffers: 1.1.1

  image: ^3.0.1
  cupertino_icons: ^1.0.6
  flutter_shaders: ^0.1.2
  get: ^4.7.2
  flutter_web_plugins:
    sdk: flutter
  path: ^1.9.1
  shader_graph:
    path: /Users/laurie/Desktop/nightmare-space/shader_graph

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

dependency_overrides:
  shader_buffers:
    path: /Users/laurie/Desktop/nightmare-git-repo/shader_buffers

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/texture/
    - assets/cubemaps/

  shaders:
    # a
    - shaders/a/A lot of spheres.frag
    - shaders/a/a study of glass.frag
    - shaders/a/Alien ocean BufferA.frag
    - shaders/a/Alien ocean.frag
    - shaders/a/Alien Space Jockey.frag
    - shaders/a/Alpha Clip 1 bit dissolve.frag
    - shaders/a/anamorphic rendering.frag
    - shaders/a/Angel.frag
    - shaders/a/Arcade Pacman.frag
    - shaders/a/Artifact at Sea.frag
    - shaders/a/Atmosphere system test.frag
    #
    # b
    - shaders/b/Balatro Background Shaders.frag
    - shaders/b/balls are rubbing.frag
    - shaders/b/Base warp fBM.frag
    - shaders/b/Black Hole ODE Geodesic Solver.frag
    - shaders/b/Black Hole Raymarcher 3 BufferA.frag
    - shaders/b/Black Hole Raymarcher 3 BufferB.frag
    - shaders/b/Black Hole Raymarcher 3 BufferC.frag
    - shaders/b/Black Hole Raymarcher 3.frag
    - shaders/b/Broken Time Gate.frag
    - shaders/b/Bubbles.frag
    - shaders/b/Bumped Sinusoidal Warp.frag
    - shaders/b/Buoy.frag
    - shaders/b/Byt3-daily-013.frag
    #
    # c
    - shaders/c/CineShader Lava.frag
    - shaders/c/Clouds-2D.frag
    - shaders/c/cobweb test.frag
    - shaders/c/Cold.frag
    - shaders/c/Colorful underwater bubbles II.frag
    - shaders/c/Combustible Voronoi.frag
    - shaders/c/Crosswarp transition.frag
    - shaders/c/Cube lines.frag
    - shaders/c/cubular.frag
    - shaders/c/Curl noise Image transition.frag
    #
    # d
    - shaders/d/Dark Transit.frag
    - shaders/d/Desire Crystal.frag
    - shaders/d/Devil Glass.frag
    - shaders/d/Digital Brain.frag
    - shaders/d/Dive to Cloud.frag
    - shaders/d/divergence-free flow curly noise.frag
    - shaders/d/dodecahedron͏ BufferA.frag
    - shaders/d/dodecahedron͏.frag
    - shaders/d/drifting.frag
    - shaders/d/Drive Home 6 - Rain Window.frag
    - shaders/d/DULL SKULL - Prometheus.frag
    - shaders/d/Dusty nebula 4.frag
    #
    # e
    - shaders/e/ED-209.frag
    - shaders/e/electron.frag
    # Elevated
    - shaders/e/Elevated BufferA.frag
    - shaders/e/Elevated.frag
    - shaders/e/EntryLevel.frag
    #
    # f
    - shaders/f/Fire.frag
    - shaders/f/Flame.frag
    - shaders/f/fractal pyramid.frag
    - shaders/f/Fractured Orb BufferA.frag
    - shaders/f/Fractured Orb.frag
    - shaders/f/Full Spectrum Cyber.frag
    #
    # g
    - shaders/g/Galaxy of Universes.frag
    - shaders/g/Galvanize.frag
    - shaders/g/Ghosts.frag
    - shaders/g/Goodbye Dream Clouds.frag
    - shaders/g/Gradient Flow.frag
    #
    # h
    - shaders/h/Hell.frag
    #
    # i
    - shaders/i/inercia intended one.frag
    - shaders/i/Ink Blot Spread.frag
    - shaders/i/Input - Time.frag
    - shaders/i/Inside the mandelbulb II BufferA.frag
    - shaders/i/Inside the mandelbulb II.frag
    - shaders/i/Inverse Bilinear.frag
    - shaders/i/Ionize.frag
    #
    # l
    - shaders/l/Landmass z-morph.frag
    - shaders/l/Let's self reflect.frag
    - shaders/l/Lights in Smoke.frag
    #
    # m
    - shaders/m/M-O (from Wall-E).frag
    - shaders/m/MacOS Monterey 2 BufferA.frag
    - shaders/m/MacOS Monterey 2.frag
    - shaders/m/MacOS Monterey wallpaper BufferA.frag
    - shaders/m/MacOS Monterey wallpaper.frag
    - shaders/m/Mandelbulb 3D Fractal.frag
    - shaders/m/Mandelbulb Deconstructed.frag
    - shaders/m/mandelbulb.frag
    - shaders/m/Mario World 1-1.frag
    - shaders/m/Metal Vortex.frag
    - shaders/m/MONSTER.frag
    - shaders/m/Monterey wannabe.frag
    #
    # n
    - shaders/n/Noise Lab (3D).frag
    - shaders/n/NotSoGreeeen - Chromatic Hole.frag
    #
    # o
    - shaders/o/Octagrams.frag
    # TODO: fix Orbital Megastructure
    # - shaders/o/Orbital Megastructure.frag
    - shaders/o/Origami.frag
    #
    # p
    - shaders/p/Page Curl Effect on Ball.frag
    - shaders/p/Palace of Mind.frag
    - shaders/p/Parallax transition with mouse.frag
    - shaders/p/Perlin sin sphere.frag
    - shaders/p/Perspex Web Lattice.frag
    - shaders/p/Phantom Star for CineShader.frag
    - shaders/p/Pig Squad 9 Year Anniversary.frag
    - shaders/p/Pistons with Motion Blur.frag
    - shaders/p/Plasma Globe.frag
    - shaders/p/Portal - iOS AR.frag
    - shaders/p/Portal - iOS AR BufferA.frag
    - shaders/p/Portal 2 Box Flip Rotation.frag
    - shaders/p/Protean clouds.frag
    - shaders/p/Pulsar Explained.frag
    #
    # r
    - shaders/r/Rainforest BufferA.frag
    - shaders/r/Rainforest.frag
    - shaders/r/Rainier mood.frag
    - shaders/r/Raymarching Basic.frag
    - shaders/r/Reclaim the streets.frag
    - shaders/r/Red-Blue Swirl.frag
    - shaders/r/Rotate And Points Circle.frag
    #
    # s
    - shaders/s/Seascape.frag
    - shaders/s/Server Room.frag
    - shaders/s/Shader Art Coding Introduction.frag
    - shaders/s/Shock Wave with Saturation.frag
    - shaders/s/simple page curl effect.frag
    - shaders/s/simple refraction test.frag
    - shaders/s/Simple ripple shader.frag
    - shaders/s/Singularity.frag
    - shaders/s/Space Curvature.frag
    - shaders/s/Sphere Gears.frag
    - shaders/s/Split Prism.frag
    - shaders/s/Spreading Frost.frag
    - shaders/s/starfield new.frag
    # TODO: fix Super Resolution
    # - shaders/s/superResolution BufferA.frag
    # - shaders/s/superResolution BufferB.frag
    # - shaders/s/superResolution BufferC.frag
    # - shaders/s/superResolution BufferD.frag
    # t
    - shaders/t/The sun, the sky and the clouds.frag
    - shaders/t/TIE Fighters.frag
    - shaders/t/Tissue.frag
    - shaders/t/tm gyroids.frag
    - shaders/t/Transition Burning.frag
    - shaders/t/Transition SST.frag
    - shaders/t/Transition with image.frag
    - shaders/t/Tunnel Cable.frag
    #
    # u
    - shaders/u/UI noise halo.frag
    - shaders/u/Underground Passageway.frag
    - shaders/u/Underground Passageway BufferA.frag
    - shaders/u/Undular Substratum.frag
    #
    # v
    - shaders/v/Very fast procedural ocean.frag
    #
    # w
    - shaders/w/Warped Extruded Skewed Grid.frag
    - shaders/w/Warping - procedural 2.frag
    - shaders/w/Water2D.frag
    - shaders/w/wavyfire.frag
    - shaders/w/Where the River Goes.frag
    #
    # z
    - shaders/z/Zippy Zaps.frag
    #
